language: c

dist: bionic

compiler:
 - clang

addons:
  apt:
    packages:
     - bison
     - autoconf
     - autogen
     - libgcrypt20-dev
     - libgnutls28-dev
     - libsqlite3-dev
     - libpq-dev
     - libmysqlclient-dev
     - python3-dev
     - libjson-c-dev
     - libxml2-dev
     - zlib1g-dev

before_script:
 - cd src
 - unset PYTHON_CFLAGS

script:
 - ./autogen.sh
 - ./configure --enable-use-ipv6 --enable-use-mccp --enable-use-json --enable-use-pcre
               --enable-use-mysql --enable-use-pgsql --enable-use-sqlite
               --enable-use-xml --enable-use-tls  --enable-use-gcrypt --enable-use-python
               --enable-malloc-trace --enable-malloc-lpc-trace  --enable-dynamic-costs
               --enable-eval-cost-trace --enable-trace-code
               EXTRA_CFLAGS="-DINSIDE_TRAVIS -Werror"
 - make
 - cd ../test && ./run.sh
