#!/bin/sh
#
# Settings for the Avalon MUDlib
#
# configure will strip this part from the script.

exec ./configure --prefix=/home/mud --libdir=/home/mud/mudlib --libexecdir=/home/mud/erq --with-setting=avalon $*
exit 1

# --- The actual settings ---

with_portno=7777
with_catch_udp_port=4246
with_max_players=200
enable_access_control=no

with_max_cost=1000000
with_catch_reserved_cost=10000
with_master_reserved_cost=0x800
enable_dynamic_costs=yes

with_time_to_clean_up=5400
with_time_to_swap=1800
with_time_to_swap_variables=3600
with_time_to_reset=2400

enable_compat_mode=no
enable_strict_euids=yes

enable_supply_parse_command=no
enable_initialization_by___init=yes

enable_smalloc_trace=yes
enable_smalloc_lpc_trace=yes

with_htable_size=16384
with_otable_size=4096

with_max_malloced=0x20000000
with_max_small_malloced=0x10000000

with_max_array_size=6000
with_max_mapping_size=40000
with_max_byte_transfer=100000
with_read_file_max_size=100000
