#!/bin/sh
#
# Settings for the Deeper Trouble II mudlib.
#
# configure will strip this part from the script.

exec ./configure --prefix=/export/home/mud --libexec=/export/home/mud/mud/erq --libdir=/export/home/mud/lib --with-setting=dt2 $*
exit 1

# --- The actual settings ---

with_portno=7680
with_udp_port=8889

with_time_to_swap=0
with_time_to_swap_variables=0
with_swap_file="/tmp/LP_SWAP.1"

with_time_to_reset=7200

enable_erq=xerq

