#!/bin/sh
#
# Settings for EotL
#
# configure will strip this part from the script.

exec ./configure --prefix=/home/mud --libdir=/home/mud/mudlib --libexecdir=/home/mud/erq --with-setting=eotl $*
exit 1

# --- The actual settings ---

with_max_array_size=16000
with_max_mapping_keys=16000
with_max_mapping_size=48000
with_read_file_max_size=3000000
with_max_byte_transfer=500000

with_hard_malloc_limit=0x6000000
with_min_malloced=0x2000000

with_time_to_clean_up=7200
with_time_to_swap=900
with_time_to_swap_variables=3600

enable_strict_euids=yes
enable_use_alists=yes

with_portno=2010

with_swap_file=etc/swap/LP_SWAP.3

with_access_file=adm/etc/ACCESS.ALLOW

enable_share_variables=yes
enable_use_pcre=no

with_max_players=100
with_allowed_ed_cmds=3

with_htable_size=65536
with_otable_size=8192
with_itable_size=512
with_apply_cache_bits=14
