#!/bin/sh
#
# Settings for the FinalFrontier mudlib.
#
# The generated config.h will not contain the additional definitions
# required by the FinalFrontier driver extensions.
#
# These additional defines are (as of 17-July-2000):
#
#  /* Include code for EFun int get_eval_time(). This EFun returns the number of
#     miliseconds since the start of the current evaluation loop. */
#  #define GET_EVAL_TIME
#
# TODO: Find a way to specify and #include host specific files into
# TOOD:: config.h - maybe test for setting/<name>.h and include if existing.
#
# configure will strip this part from the script.

exec ./configure --prefix=/mud --libexecdir=/mud/erq --libdir=/mud/mudlib --enable-erq=xerq --with-setting=finalfrontier $*
exit 1

# --- The actual settings ---

# --- Runtime limits ---

# --- Timing ---
with_time_to_swap=1800
with_time_to_swap_variables=3600
with_time_to_reset=1800

# --- Memory ---
with_reserved_user_size=0x400000
with_reserved_master_size=0x100000
with_reserved_system_size=0x200000
with_hard_malloc_limit=0x16000000
enable_min_malloced=yes
with_min_malloced=0x8000000
enable_min_small_malloced=yes
with_min_small_malloced=0x4000000

# --- Interpreter ---
with_max_cost=1000000
with_max_trace=85
with_max_user_trace=80
 
# --- Communication ---
with_portno=7600
with_udp_port=7610

#----------- Compilation Options ----------
enable_use_mccp=yes

enable_malloc_trace=yes
enable_malloc_lpc_trace=yes

# --- Access Control ---
enable_access_control=yes

# --- Language ---
enable_use_parse_command=yes
enable_use_mysql=yes
enable_use_alists=yes
enable_use_pcre=no

# --- Runtime limits ---
with_catch_reserved_cost=10000
with_master_reserved_cost=0x800
with_max_players=200

# --- Compiler ---

# --- Internal Tables ---
with_htable_size=0x10000
with_otable_size=0x4000
with_apply_cache_bits=14
