#!/bin/sh
#
# LDMud settings for Forgotten Dreams (DreamsLib)
#

exec ./configure --prefix=/home/forgotten --libexecdir=/home/forgotten/lib/erq --libdir=/home/forgotten/lib/mudlib --with-setting=forgottendreams $*
exit 1

# --- The actual settings---

enable_erq=erq
enable_compat_mode=no
enable_strict_euids=yes
enable_supply_parse_command=no
enable_initialization_by___init=no
enable_use_mysql=yes
enable_lpc_nosave=yes
enable_use_deprecated=no
enable_dynamic_costs=yes

with_master_name=kernel/master
with_swap_file=LD_SWAP.3
with_max_array_size=5000
with_max_mapping_size=10000
with_max_local=100
