#!/bin/sh
#
# Settings for the Gestrandet mudlib.
#
# configure will strip this part from the script.

exec ./configure --prefix=/home/urv/mud/ --libdir=/home/urv/mud/lib/gestrandet --with-setting=gestrandet $*
exit 1

# --- The actual settings ---
# with_swap_file=/etc/SWAP_FILE

# --- Runtime limits ---
with_read_file_max_size=100000

# --- Timing ---
with_time_to_clean_up=5400
with_time_to_swap=1800
with_time_to_swap_variables=3600
with_time_to_reset=2400

# --- Memory ---
with_reserved_user_size=0x400000
with_reserved_master_size=0x100000
with_reserved_system_size=0x200000
with_hard_malloc_limit=0x1c000000
enable_min_malloced=yes
with_min_malloced=0x8000000
enable_min_small_malloced=yes
with_min_small_malloced=0x4000000

# --- Interpreter ---
enable_strict_euids=yes
with_max_cost=450000

# --- Communication ---
with_portno=3333
with_udp_port=3335

#----------- Compilation Options ----------
enable_malloc_trace=yes
enable_malloc_lpc_trace=yes
enable_use_pthreads=yes

# --- Wizlist ---
with_wizlist_file=/etc/WIZLIST

# --- Access Control ---
enable_access_control=no

# --- Language ---
enable_supply_parse_command=no
enable_use_mysql=yes
enable_use_deprecated=no

# --- Runtime limits ---
with_catch_reserved_cost=0x10000
with_master_reserved_cost=0x4000
enable_dynamic_costs=yes
with_max_trace=80
with_max_players=200

# --- Compiler ---

# --- Internal Tables ---
with_htable_size=0x10000
with_otable_size=0x4000
with_apply_cache_bits=14

# --- Profiling ---

# --- Standard Debugging ---
enable_check_strings=no

# --- Specific Debugging ---
