#!/bin/sh
#
# Settings for the Heaven7 mudlib.
#
# configure will strip this part from the script.

exec ./configure --with-setting=heaven7 $*
exit 1

# --- The actual settings ---

with_master_name=secure/master
enable_compat_mode=yes
enable_strict_euids=no
enable_lpc_nosave=no

enable_access_control=no
with_portno=6100
with_max_cost=900000
with_swap_file=log/LP_SWAP.3
with_catch_udp_port=6099
with_time_to_clean_up=5400
with_time_to_reset=900
with_max_bits=1200
with_reserved_user_size=800000
with_reserved_master_size=50000
with_reserved_system_size=100000
enable_initialization_by___init=no

