#!/bin/sh
#
# Settings for a native-mode driver.
#
# configure will strip this part from the script.

exec ./configure --with-setting=native $*
exit 1

# --- The actual settings ---

with_master_name=secure/master
enable_compat_mode=no
enable_strict_euids=yes
enable_use_alists=yes
enable_use_pcre=no
