#!/bin/sh
#
# Settings for Tamedhon (TD Mudlib 2.0).
#
# configure will strip this part from the script.

MUDHOME=/home/mud

exec ./configure --prefix=${MUDHOME}/ --libdir=${MUDHOME}/mudlib --bindir=${MUDHOME}/bin --libexecdir=${MUDHOME}/bin --with-setting=tamedhon $*
exit $?

# --- Timing ---
with_time_to_reset=3600
with_time_to_clean_up=5400
with_alarm_time=1
with_heart_beat_interval=2

# --- Swap ---
with_time_to_swap=-1
with_time_to_swap_variables=-1
with_swap_file=Swap_File

# --- Memory ---
with_hard_malloc_limit=0
with_soft_malloc_limit=0

# --- Interpreter ---
with_max_cost=9000000
with_max_trace=1300
with_max_user_trace=1200

# --- Communication ---
with_portno=4711
with_udp_port=4246
enable_use_tls=yes
enable_use_xml=xml2
enable_use_json=yes
enable_use_sqlite=yes
enable_use_mccp=yes

# --- ERQ ---
enable_erq=xerq
with_erq_dir=${MUDHOME}/bin

# --- Wizlist ---
with_wizlist_file=no

# --- Access Control ---
enable_access_control=no

# --- Compilation Options ---
enable_malloc_trace=no
enable_malloc_lpc_trace=no
enable_eval_cost_trace=yes
enable_use_pcre=no
enable_use_parse_command=no
enable_use_mysql=no
enable_udp_send=yes
enable_strict_euids=yes

# --- Runtime limits ---
with_catch_reserved_cost=40000
with_master_reserved_cost=10000
with_max_players=225
with_max_array_size=20000
with_max_mapping_keys=20000
with_max_mapping_size=60000
with_max_byte_transfer=200000
with_read_file_max_size=200000
