#!/bin/sh
#
# Settings for the UNItopia mudlib.
#
# configure will strip this part from the script.

exec ./configure --prefix=/UNItopia/mudadm/magyra --libexecdir=/UNItopia/mudadm/magyra/erq --libdir=/tmp --with-setting=unitopia EXTRA_CFLAGS=-m32 LDFLAGS=-m32 $*
exit 1

# --- The actual settings ---

# --- Runtime limits ---
with_max_array_size=10000
with_max_mapping_keys=10000
with_max_mapping_size=100000
with_max_byte_transfer=100000
with_read_file_max_size=100000
with_write_buffer_max_size=524288

# --- Timing ---
with_time_to_clean_up=5400
with_time_to_swap=1800
with_time_to_swap_variables=3600
with_time_to_reset=2400
with_alarm_time=1
with_heart_beat_interval=2
enable_synchronous_heart_beat=no

# --- Memory ---
with_reserved_user_size=0x400000
with_reserved_master_size=0x100000
with_reserved_system_size=0x200000
with_hard_malloc_limit=0x60000000
enable_min_malloced=yes
with_min_malloced=0x8000000
enable_min_small_malloced=yes
with_min_small_malloced=0x4000000

# --- Interpreter ---
enable_strict_euids=yes
with_max_cost=500000

# --- Communication ---
with_portno=3333
with_udp_port=3335
enable_use_ipv6=yes
enable_use_mccp=yes
enable_use_tls=gnu
with_tls_keyfile=no

#----------- Compilation Options ----------
enable_malloc_trace=yes
enable_malloc_lpc_trace=yes
enable_use_pthreads=no

# --- Wizlist ---
with_wizlist_file=no

# --- Access Control ---
enable_access_control=no

# --- Language ---
enable_use_set_light=no
enable_use_parse_command=no
enable_use_mysql=no
enable_use_sqlite=yes
enable_use_xml=xml2
enable_use_deprecated=no
enable_use_pcre=no
enable_lpc_array_calls=yes

# --- Runtime limits ---
with_catch_reserved_cost=0x10000
with_master_reserved_cost=0x4000
enable_dynamic_costs=yes
enable_eval_cost_trace=yes
with_max_trace=80
with_max_players=200

# --- Compiler ---

# --- Internal Tables ---
with_htable_size=0x10000
with_otable_size=0x4000
with_apply_cache_bits=14

# --- Profiling ---

# --- Standard Debugging ---
enable_check_strings=no

# --- Specific Debugging ---
enable_check_object_stat=no

# --- Additional tools ---
enable_erq=xerq
