#!/bin/sh
#
# Settings for the UNItopia mudlib.
#
# configure will strip this part from the script.

exec ./configure --prefix=/UNItopia/mudadm/magyra --libexecdir=/UNItopia/mudadm/magyra/erq --with-setting=unitopia $*
exit 1

# --- The actual settings ---

# --- Runtime limits ---

# --- Timing ---
with_time_to_clean_up=5400
with_time_to_swap=1800
with_time_to_swap_variables=3600
with_time_to_reset=2400

# --- Memory ---
with_reserved_user_size=0x400000
with_reserved_master_size=0x100000
with_reserved_system_size=0x200000
with_max_malloced=0x14000000

# --- Interpreter ---
enable_strict_euids=yes
with_max_cost=400000

# --- Communication ---
with_portno=3333
with_udp_port=3335

#----------- Compilation Options ----------
enable_malloc_trace=yes
enable_malloc_lpc_trace=yes

# --- Access Control ---
enable_access_control=no

# --- Communication ---

# --- Language ---
enable_supply_parse_command=no
enable_use_mysql=yes

# --- Runtime limits ---
with_catch_reserved_cost=10000
with_master_reserved_cost=0x800
with_max_players=200

# --- Compiler ---

# --- Internal Tables ---
with_htable_size=0x10000
with_otable_size=0x4000
with_apply_cache_bits=14


