#!/bin/sh
#
# Settings for the WunderLand mudlib.
#
# configure will strip this part from the script.

exec ./configure --prefix=/mud --exec-prefix=/mud --bindir=/mud/bin --libdir=/mud/mudlib --libexecdir=/mud/bin/erq_dir --with-setting=wunderland $*

exit 1

# --- The actual settings ---

enable_erq=xerq
enable_access_control=no
enable_access_log=no
enable_align_functions=yes
enable_compat_mode=no
enable_strict_euids=yes
enable_supply_parse_command=yes
enable_initialization_by___init=yes
enable_comm_stat=yes
enable_apply_cache_stat=yes
enable_smalloc_trace=no
enable_smalloc_lpc_trace=no
enable_dynamic_costs=no
enable_rxcache_table=yes
with_access_file=ACCESS.ALLOW
with_access_log=access.allow.log
with_erq_max_reply=1024
with_erq_max_send=1024
with_max_log_size=50000
with_read_file_max_size=50000
with_master_name=secure/master
with_time_to_clean_up=14400
with_time_to_swap=5400
with_time_to_swap_variables=7200
with_time_to_reset=3600
with_evaluator_stack_size=2000
with_max_user_trace=60
with_max_trace=65
with_compiler_stack_size=400
with_max_bits=6144
with_portno=4711
with_maxnumports=3
with_max_cost=1000000
with_catch_reserved_cost=2000
with_master_reserved_cost=0x200
with_swap_file=LP_SWAP.3
with_max_array_size=5000
with_max_mapping_size=5000
with_max_players=60
with_max_local=50
with_allowed_ed_cmds=20
with_reserved_user_size=800000
with_reserved_master_size=100000
with_reserved_system_size=200000
with_htable_size=8192
with_itable_size=256
with_otable_size=4096
with_defmax=65000
with_apply_cache_bits=12
with_rxcache_table=16384
with_max_byte_transfer=200000
with_udp_port=4246
with_set_buffer_size_max=65536
with_min_malloced=0
#with_min_malloced=0x1000000
with_max_malloced=0x6000000
with_total_trace_length=0x1000
enable_use_alists=yes
enable_use_ipv6=yes
