This file lists all(?) the changes that has been done for the batmud branch.

11-Nov-2001 (Tomba)  (5)
    - New push_line(). Pushes the lines in front of the buffer.

10-Nov-2001 (Tomba)  (4)
    - Changed word to return arrays. Seems to fix mem leaks and crashes

07-Nov-2001 (Moght)  (3)
    - Attached 'word' command stuff from old GD

31-Oct-2001 (Tomba)  (2)
    - (comm.c func_defs) push_line
    - (comm.c, backend.c) ! -> @

14-Oct-2001 (Tomba)  (1)
    - First version in cvs
    - Someone should write here the changes that has already been done

