#pragma strong_types
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
// The lexer must refill its input before the error below.
void run()
{
    int count = "three";
}
